{"uuid": "b221f5ac-187a-4087-b057-78fd3dfd8292", "children": ["48903ecd-d405-4f67-bdb2-d9e5189e1f7f", "3978fac5-f304-4d99-a9b2-4a7d7699c823"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018C2FAF3AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\DELL\\PycharmProjects\\Amazon\\Testes\\conftest.py\", line 16, in setup\n    driver = webdriver.Chrome(ChromeDriverManager().install())\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\chrome.py\", line 32, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\manager.py\", line 23, in _get_driver_path\n    driver_version = driver.get_version()\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\driver.py\", line 40, in get_version\n    return self.get_latest_release_version()\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\webdriver_manager\\driver.py\", line 70, in get_latest_release_version\n    resp = requests.get(\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1647094042107, "stop": 1647094044000}], "start": 1647094042107, "stop": 1647094044672}